# Enable this option to log more verbose output. Makes debugging easier. 
debug: false

# Set location of log files
logFolder: "logs"

# Choose if you want to participate in beta updates
updateBranch: "stable"
